// MVC Flow Sketch - Stage 0 validation
// Demonstrates: Router → Controller → Model → View → HTML

import initSqlJs from 'sql.js';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { ActiveRecord, setDatabase, attr_accessor } from './active_record.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));

// === Database Setup ===
const SQL = await initSqlJs({
  locateFile: file => join(__dirname, 'node_modules', 'sql.js', 'dist', file)
});
const db = new SQL.Database();
setDatabase(db);

db.run(`
  CREATE TABLE articles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    body TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
  )
`);

// === Model ===
class Article extends ActiveRecord {
  static tableName = 'articles';
}
attr_accessor(Article, 'title', 'body', 'created_at');

// Seed data
Article.create({ title: 'Hello Rails', body: 'I am on Rails!' });
Article.create({ title: 'Getting Started', body: 'Welcome to the blog.' });

// === View (simulates transpiled ERB) ===
// In reality, this would be generated by the ERB filter from .erb files

const views = {
  'articles/index': ({ articles }) => {
    let html = '<h1>Articles</h1>\n<ul>\n';
    for (const article of articles) {
      html += `  <li><a href="/articles/${article.id}">${article.title}</a></li>\n`;
    }
    html += '</ul>\n';
    html += '<a href="/articles/new">New Article</a>';
    return html;
  },

  'articles/show': ({ article }) => {
    return `<h1>${article.title}</h1>
<p>${article.body}</p>
<p><small>Created: ${article.created_at}</small></p>
<a href="/articles">Back</a> | <a href="/articles/${article.id}/edit">Edit</a>`;
  },

  'articles/new': () => {
    return `<h1>New Article</h1>
<form action="/articles" method="post">
  <p><label>Title: <input type="text" name="article[title]"></label></p>
  <p><label>Body: <textarea name="article[body]"></textarea></label></p>
  <p><button type="submit">Create Article</button></p>
</form>
<a href="/articles">Back</a>`;
  },

  'articles/edit': ({ article }) => {
    return `<h1>Edit Article</h1>
<form action="/articles/${article.id}" method="post">
  <input type="hidden" name="_method" value="patch">
  <p><label>Title: <input type="text" name="article[title]" value="${article.title}"></label></p>
  <p><label>Body: <textarea name="article[body]">${article.body}</textarea></label></p>
  <p><button type="submit">Update Article</button></p>
</form>
<a href="/articles/${article.id}">Cancel</a>`;
  }
};

function render(template, locals = {}) {
  const viewFn = views[template];
  if (!viewFn) throw new Error(`Template not found: ${template}`);
  return viewFn(locals);
}

// === Controller ===
class ArticlesController {
  // GET /articles
  index() {
    const articles = Article.all();
    return render('articles/index', { articles });
  }

  // GET /articles/:id
  show(params) {
    const article = Article.find(params.id);
    return render('articles/show', { article });
  }

  // GET /articles/new
  new() {
    return render('articles/new');
  }

  // POST /articles
  create(params) {
    const article = Article.create(params.article);
    return { redirect: `/articles/${article.id}` };
  }

  // GET /articles/:id/edit
  edit(params) {
    const article = Article.find(params.id);
    return render('articles/edit', { article });
  }

  // PATCH /articles/:id
  update(params) {
    const article = Article.find(params.id);
    article.update(params.article);
    return { redirect: `/articles/${article.id}` };
  }

  // DELETE /articles/:id
  destroy(params) {
    const article = Article.find(params.id);
    article.destroy();
    return { redirect: '/articles' };
  }
}

// === Router ===
const routes = [
  { method: 'GET',    path: /^\/articles$/,              action: 'index' },
  { method: 'GET',    path: /^\/articles\/new$/,         action: 'new' },
  { method: 'GET',    path: /^\/articles\/(\d+)$/,       action: 'show' },
  { method: 'GET',    path: /^\/articles\/(\d+)\/edit$/, action: 'edit' },
  { method: 'POST',   path: /^\/articles$/,              action: 'create' },
  { method: 'PATCH',  path: /^\/articles\/(\d+)$/,       action: 'update' },
  { method: 'DELETE', path: /^\/articles\/(\d+)$/,       action: 'destroy' },
];

function dispatch(method, path, body = {}) {
  for (const route of routes) {
    if (route.method !== method) continue;
    const match = path.match(route.path);
    if (match) {
      const params = { ...body };
      if (match[1]) params.id = parseInt(match[1]);

      const controller = new ArticlesController();
      return controller[route.action](params);
    }
  }
  return { status: 404, body: 'Not Found' };
}

// === Simulate Requests ===
console.log('=== MVC Flow Sketch ===\n');

console.log('--- GET /articles (index) ---');
console.log(dispatch('GET', '/articles'));
console.log();

console.log('--- GET /articles/1 (show) ---');
console.log(dispatch('GET', '/articles/1'));
console.log();

console.log('--- GET /articles/new ---');
console.log(dispatch('GET', '/articles/new'));
console.log();

console.log('--- POST /articles (create) ---');
const createResult = dispatch('POST', '/articles', {
  article: { title: 'Third Post', body: 'Created via controller' }
});
console.log(createResult);
console.log();

console.log('--- GET /articles (after create) ---');
console.log(dispatch('GET', '/articles'));
console.log();

console.log('--- GET /articles/3/edit ---');
console.log(dispatch('GET', '/articles/3/edit'));
console.log();

console.log('--- PATCH /articles/3 (update) ---');
const updateResult = dispatch('PATCH', '/articles/3', {
  article: { title: 'Third Post (Updated)', body: 'Modified content' }
});
console.log(updateResult);
console.log();

console.log('--- GET /articles/3 (after update) ---');
console.log(dispatch('GET', '/articles/3'));
console.log();

console.log('--- DELETE /articles/3 ---');
console.log(dispatch('DELETE', '/articles/3'));
console.log();

console.log('--- GET /articles (after delete) ---');
console.log(dispatch('GET', '/articles'));
console.log();

db.close();
console.log('=== Sketch complete ===');
