source 'https://rubygems.org'

gem 'rake'
gem 'wunderbar', '>= 0.23.0'
gem 'rack', '~> 2.2'
gem 'ruby2js', path: File.expand_path('..', __dir__)
gem 'sinatra'
gem 'nokogiri'  # includes HTML5 parsing (formerly nokogumbo)
gem 'execjs'
gem 'opal', '~> 1.0'
gem 'regexp_parser'

group :demo do
  gem 'puma'
end
