# frozen_string_literal: true

require 'optparse'

module Ruby2JS
  module CLI
    module Deploy
      DIST_DIR = 'dist'

      # Valid deploy targets and their required databases
      TARGETS = {
        'vercel' => %w[turso neon planetscale dexie],
        'cloudflare' => %w[d1 turso dexie]
      }.freeze

      class << self
        def run(args)
          options = parse_options(args)

          validate_rails_app!
          check_installation!
          validate_target!(options)

          deploy(options)
        end

        private

        def parse_options(args)
          options = {
            target: ENV['JUNTOS_TARGET'],
            database: ENV['JUNTOS_DATABASE'],
            verbose: false,
            skip_build: false
          }

          parser = OptionParser.new do |opts|
            opts.banner = "Usage: juntos deploy [options]"
            opts.separator ""
            opts.separator "Build and deploy to a serverless platform."
            opts.separator ""
            opts.separator "Options:"

            opts.on("-t", "--target TARGET", TARGETS.keys, "Deploy target: #{TARGETS.keys.join(', ')}") do |target|
              options[:target] = target
            end

            opts.on("-d", "--database ADAPTER", "Database adapter for deployment") do |db|
              options[:database] = db
            end

            opts.on("--skip-build", "Skip the build step (use existing dist/)") do
              options[:skip_build] = true
            end

            opts.on("-v", "--verbose", "Show detailed output") do
              options[:verbose] = true
            end

            opts.on("-h", "--help", "Show this help message") do
              puts opts
              exit
            end
          end

          parser.parse!(args)
          options
        end

        def validate_rails_app!
          unless File.directory?("app") && File.directory?("config")
            abort "Error: Not a Rails-like application directory.\n" \
                  "Run this command from your Rails application root."
          end
        end

        def check_installation!
          package_json = File.join(DIST_DIR, 'package.json')

          unless File.exist?(package_json)
            abort "Error: #{package_json} not found.\n" \
                  "Run 'juntos install' first to set up the project."
          end
        end

        def validate_target!(options)
          unless options[:target]
            abort "Error: Deploy target required.\n" \
                  "Use -t/--target to specify: #{TARGETS.keys.join(', ')}\n\n" \
                  "Example: juntos deploy -t vercel -d turso"
          end

          unless TARGETS.key?(options[:target])
            abort "Error: Unknown target '#{options[:target]}'.\n" \
                  "Valid targets: #{TARGETS.keys.join(', ')}"
          end

          if options[:database]
            valid_dbs = TARGETS[options[:target]]
            unless valid_dbs.include?(options[:database])
              abort "Error: Database '#{options[:database]}' not supported for #{options[:target]}.\n" \
                    "Valid databases: #{valid_dbs.join(', ')}"
            end
          end
        end

        def deploy(options)
          target = options[:target]

          # Build first unless skipped
          unless options[:skip_build]
            puts "Building for #{target}..."
            require 'ruby2js/rails/builder'
            SelfhostBuilder.new(nil, target: target).build
          end

          # Generate platform config
          generate_platform_config(target, options)

          # Run platform deploy
          run_platform_deploy(target, options)
        end

        def generate_platform_config(target, options)
          case target
          when 'vercel'
            generate_vercel_config(options)
          when 'cloudflare'
            generate_cloudflare_config(options)
          end
        end

        def generate_vercel_config(options)
          vercel_json = {
            "version" => 2,
            "builds" => [
              { "src" => "api/**/*.js", "use" => "@vercel/node" }
            ],
            "routes" => [
              { "src" => "/app/assets/(.*)", "dest" => "/app/assets/$1" },
              { "src" => "/(.*)", "dest" => "/api/[[...path]].js" }
            ]
          }

          File.write(File.join(DIST_DIR, 'vercel.json'), JSON.pretty_generate(vercel_json))
          puts "  Generated vercel.json"

          # Generate API handler
          api_dir = File.join(DIST_DIR, 'api')
          Dir.mkdir(api_dir) unless File.directory?(api_dir)

          api_handler = <<~JS
            // Vercel Edge/Node handler - auto-generated by Juntos
            import { Application } from '../config/routes.js';

            export default async function handler(req, res) {
              return Application.handleRequest(req, res);
            }

            export const config = {
              runtime: 'nodejs20.x'
            };
          JS

          File.write(File.join(api_dir, '[[...path]].js'), api_handler)
          puts "  Generated api/[[...path]].js"
        end

        def generate_cloudflare_config(options)
          wrangler_toml = <<~TOML
            name = "#{File.basename(Dir.pwd)}"
            main = "worker.js"
            compatibility_date = "#{Date.today}"

            [site]
            bucket = "./public"
          TOML

          File.write(File.join(DIST_DIR, 'wrangler.toml'), wrangler_toml)
          puts "  Generated wrangler.toml"

          # Generate worker
          worker_js = <<~JS
            // Cloudflare Worker - auto-generated by Juntos
            import { Application } from './config/routes.js';

            export default {
              async fetch(request, env, ctx) {
                return Application.handleRequest(request, env);
              }
            };
          JS

          File.write(File.join(DIST_DIR, 'worker.js'), worker_js)
          puts "  Generated worker.js"
        end

        def run_platform_deploy(target, options)
          puts "\nDeploying to #{target}..."

          case target
          when 'vercel'
            Dir.chdir(DIST_DIR) do
              if system("which vercel > /dev/null 2>&1")
                exec("vercel", "--prod")
              else
                puts "\nTo deploy, install the Vercel CLI and run:"
                puts "  cd dist && vercel --prod"
              end
            end
          when 'cloudflare'
            Dir.chdir(DIST_DIR) do
              if system("which wrangler > /dev/null 2>&1")
                exec("wrangler", "deploy")
              else
                puts "\nTo deploy, install Wrangler and run:"
                puts "  cd dist && wrangler deploy"
              end
            end
          end
        end
      end
    end
  end
end
