source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "bridgetown", "~> 2.0"
gem "ruby2js", path: "../"

gem "bridgetown-seo-tag", "~> 7.0"
gem "bridgetown-feed", "~> 4.0"
gem "bridgetown-quick-search", "~> 3.0"

group :demo do
  gem 'rake'
  gem 'wunderbar'
  gem 'opal', '~> 1.8'
  gem 'base64' # Required for Opal on Ruby 3.4+
end

gem "puma", "~> 6.0"

gem "bridgetown-svg-inliner", "~> 2.0"
